"""Content generation module for creating presentation slides and content."""

import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class ContentGenerator:
    """Generates slide content and text based on strategy and research."""

    def __init__(self):
        """Initialize content generator."""
        logger.info("ContentGenerator initialized")

    async def generate_slides(self, strategy: Dict[str, Any], research: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate slides based on strategy and research.

        Args:
            strategy: Content strategy from ContentStrategistAgent
            research: Research data from ResearchAnalystAgent

        Returns:
            List of slide content dictionaries
        """
        logger.debug("Generating slides")

        slides = []

        # Title slide
        slides.append({
            "type": "title",
            "title": "Presentation Title",
            "subtitle": "Generated by AI Presentation System",
        })

        # Content slides
        for i, section in enumerate(strategy.get("outline", [])):
            slides.append({
                "type": "content",
                "slide_number": i + 1,
                "title": section.get("section", f"Section {i + 1}"),
                "content": section.get("key_points", []),
            })

        # Conclusion slide
        slides.append({
            "type": "conclusion",
            "title": "Summary",
            "content": strategy.get("content_flow", []),
        })

        logger.info(f"Generated {len(slides)} slides")
        return slides

    async def generate_notes(self, slides: List[Dict[str, Any]]) -> Dict[str, str]:
        """Generate speaker notes for each slide."""
        notes = {}
        for slide in slides:
            slide_num = slide.get("slide_number", "title")
            notes[f"slide_{slide_num}"] = f"Notes for {slide.get('title', 'slide')}"
        return notes
